[2014-09-11 00:07:10] log.ERROR: exception 'InvalidArgumentException' with message 'View [admin.profile.index] not found.' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php:135 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php(76): Illuminate\View\FileViewFinder->findInPaths('admin.profile.i...', Array) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Environment.php(115): Illuminate\View\FileViewFinder->find('admin.profile.i...') #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\View\Environment->make('admin.profile.i...') #3 F:\xampp\htdocs\Forex\app\controllers\AdminController.php(41): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #4 F:\xampp\htdocs\Forex\app\controllers\AdminController.php(41): Illuminate\Support\Facades\View::make('admin.profile.i...') #5 [internal function]: AdminController->index('doimatkhau') #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('index', Array) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('doimatkhau') #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #11 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #15 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #16 {main} [] []
[2014-09-11 02:53:27] log.ERROR: exception 'InvalidArgumentException' with message 'View [guest.relations.index] not found.' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php:135 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php(76): Illuminate\View\FileViewFinder->findInPaths('guest.relations...', Array) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Environment.php(115): Illuminate\View\FileViewFinder->find('guest.relations...') #2 F:\xampp\htdocs\Forex\app\storage\views\16edffd3a7125820037362f0a77d68e1(24): Illuminate\View\Environment->make('guest.relations...', Array) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('F:\xampp\htdocs...') #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('F:\xampp\htdocs...', Array) #5 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('F:\xampp\htdocs...', Array) #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents() #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Http\Response.php(70): Illuminate\View\View->render() #8 F:\xampp\htdocs\Forex\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #11 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'show', Object(Illuminate\View\View)) #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'show', Array) #13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('chienluoc', 'forex', '121') #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #15 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #16 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #17 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #18 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #19 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #20 {main} [] []
[2014-09-11 02:53:50] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in F:\xampp\htdocs\Forex\app\storage\views\4e94f24fd713ddda14334686d71590d9:15 Stack trace: #0 F:\xampp\htdocs\Forex\app\storage\views\4e94f24fd713ddda14334686d71590d9(15): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'F:\xampp\htdocs...', 15, Array) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('F:\xampp\htdocs...') #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('F:\xampp\htdocs...', Array) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('F:\xampp\htdocs...', Array) #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents() #5 F:\xampp\htdocs\Forex\app\storage\views\16edffd3a7125820037362f0a77d68e1(24): Illuminate\View\View->render() #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('F:\xampp\htdocs...') #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('F:\xampp\htdocs...', Array) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('F:\xampp\htdocs...', Array) #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents() #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Http\Response.php(70): Illuminate\View\View->render() #11 F:\xampp\htdocs\Forex\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'show', Object(Illuminate\View\View)) #15 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'show', Array) #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('chienluoc', 'forex', '121') #17 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #18 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #19 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #20 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #23 {main} [] []
[2014-09-11 02:54:22] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in F:\xampp\htdocs\Forex\app\storage\views\4e94f24fd713ddda14334686d71590d9:15 Stack trace: #0 F:\xampp\htdocs\Forex\app\storage\views\4e94f24fd713ddda14334686d71590d9(15): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'F:\xampp\htdocs...', 15, Array) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('F:\xampp\htdocs...') #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('F:\xampp\htdocs...', Array) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('F:\xampp\htdocs...', Array) #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents() #5 F:\xampp\htdocs\Forex\app\storage\views\16edffd3a7125820037362f0a77d68e1(24): Illuminate\View\View->render() #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('F:\xampp\htdocs...') #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('F:\xampp\htdocs...', Array) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('F:\xampp\htdocs...', Array) #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents() #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Http\Response.php(70): Illuminate\View\View->render() #11 F:\xampp\htdocs\Forex\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'show', Object(Illuminate\View\View)) #15 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'show', Array) #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('chienluoc', 'forex', '121') #17 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #18 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #19 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #20 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #23 {main} [] []
[2014-09-11 03:12:17] log.ERROR: exception 'ErrorException' with message 'Undefined variable: alias' in F:\xampp\htdocs\Forex\app\controllers\GuestController.php:412 Stack trace: #0 F:\xampp\htdocs\Forex\app\controllers\GuestController.php(412): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'F:\xampp\htdocs...', 412, Array) #1 [internal function]: GuestController->showOthers('sangd', '21') #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('showOthers', Array) #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'showOthers', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('sangd', '21') #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-09-11 03:16:20] log.ERROR: exception 'ErrorException' with message 'Undefined variable: newthreads' in F:\xampp\htdocs\Forex\app\storage\views\62e7937ce16d04b3bd273e48f2f21128:8 Stack trace: #0 F:\xampp\htdocs\Forex\app\storage\views\62e7937ce16d04b3bd273e48f2f21128(8): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'F:\xampp\htdocs...', 8, Array) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('F:\xampp\htdocs...') #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('F:\xampp\htdocs...', Array) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('F:\xampp\htdocs...', Array) #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents() #5 F:\xampp\htdocs\Forex\app\storage\views\16edffd3a7125820037362f0a77d68e1(27): Illuminate\View\View->render() #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('F:\xampp\htdocs...') #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('F:\xampp\htdocs...', Array) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('F:\xampp\htdocs...', Array) #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents() #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Http\Response.php(70): Illuminate\View\View->render() #11 F:\xampp\htdocs\Forex\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'showOthers', Object(Illuminate\View\View)) #15 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'showOthers', Array) #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('kienthuc', '37') #17 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #18 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #19 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #20 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #23 {main} [] []
[2014-09-11 03:17:16] log.ERROR: exception 'InvalidArgumentException' with message 'View [guest.relations.ajaxpagination_new] not found.' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php:135 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php(76): Illuminate\View\FileViewFinder->findInPaths('guest.relations...', Array) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Environment.php(115): Illuminate\View\FileViewFinder->find('guest.relations...') #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(209): Illuminate\View\Environment->make('guest.relations...', Array) #3 F:\xampp\htdocs\Forex\app\controllers\GuestController.php(401): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #4 F:\xampp\htdocs\Forex\app\controllers\GuestController.php(401): Illuminate\Support\Facades\View::make('guest.relations...', Array) #5 [internal function]: GuestController->show('news', 'tin_nn', '127') #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('show', Array) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'show', Array) #9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('news', 'tin_nn', '127') #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #11 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #15 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #16 {main} [] []
[2014-09-11 03:36:05] log.ERROR: exception 'ErrorException' with message 'Undefined variable: viewsthreads' in F:\xampp\htdocs\Forex\app\storage\views\859a5d33391c0650d2593b80f4a21d06:8 Stack trace: #0 F:\xampp\htdocs\Forex\app\storage\views\859a5d33391c0650d2593b80f4a21d06(8): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'F:\xampp\htdocs...', 8, Array) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('F:\xampp\htdocs...') #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('F:\xampp\htdocs...', Array) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('F:\xampp\htdocs...', Array) #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents() #5 F:\xampp\htdocs\Forex\app\storage\views\16edffd3a7125820037362f0a77d68e1(30): Illuminate\View\View->render() #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('F:\xampp\htdocs...') #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('F:\xampp\htdocs...', Array) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('F:\xampp\htdocs...', Array) #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents() #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Http\Response.php(70): Illuminate\View\View->render() #11 F:\xampp\htdocs\Forex\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'showOthers', Object(Illuminate\View\View)) #15 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'showOthers', Array) #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('kinhnghiem', '39') #17 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #18 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #19 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #20 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #23 {main} [] []
[2014-09-11 04:11:05] log.ERROR: exception 'ErrorException' with message 'Undefined variable: viewsthreads' in F:\xampp\htdocs\Forex\app\storage\views\859a5d33391c0650d2593b80f4a21d06:8 Stack trace: #0 F:\xampp\htdocs\Forex\app\storage\views\859a5d33391c0650d2593b80f4a21d06(8): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'F:\xampp\htdocs...', 8, Array) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('F:\xampp\htdocs...') #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('F:\xampp\htdocs...', Array) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('F:\xampp\htdocs...', Array) #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents() #5 F:\xampp\htdocs\Forex\app\storage\views\18c1984ecf4553a7f11daee8b101fc55(104): Illuminate\View\View->render() #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('F:\xampp\htdocs...') #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('F:\xampp\htdocs...', Array) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('F:\xampp\htdocs...', Array) #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents() #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Http\Response.php(70): Illuminate\View\View->render() #11 F:\xampp\htdocs\Forex\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'index', Object(Illuminate\View\View)) #15 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #17 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #18 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #19 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #20 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #23 {main} [] []
[2014-09-11 04:11:25] log.ERROR: exception 'InvalidArgumentException' with message 'View [guest.relations.index_news] not found.' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php:135 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php(76): Illuminate\View\FileViewFinder->findInPaths('guest.relations...', Array) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Environment.php(115): Illuminate\View\FileViewFinder->find('guest.relations...') #2 F:\xampp\htdocs\Forex\app\storage\views\18c1984ecf4553a7f11daee8b101fc55(104): Illuminate\View\Environment->make('guest.relations...', Array) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('F:\xampp\htdocs...') #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('F:\xampp\htdocs...', Array) #5 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('F:\xampp\htdocs...', Array) #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents() #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Http\Response.php(70): Illuminate\View\View->render() #8 F:\xampp\htdocs\Forex\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #11 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'index', Object(Illuminate\View\View)) #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #15 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #16 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #17 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #18 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #19 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #20 {main} [] []
[2014-09-11 04:14:38] log.ERROR: exception 'ErrorException' with message 'Undefined variable: viewsthreads' in F:\xampp\htdocs\Forex\app\storage\views\859a5d33391c0650d2593b80f4a21d06:8 Stack trace: #0 F:\xampp\htdocs\Forex\app\storage\views\859a5d33391c0650d2593b80f4a21d06(8): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'F:\xampp\htdocs...', 8, Array) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('F:\xampp\htdocs...') #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('F:\xampp\htdocs...', Array) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('F:\xampp\htdocs...', Array) #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents() #5 F:\xampp\htdocs\Forex\app\storage\views\f6f3b030e2bcfd87bf68da5b89beed1e(13): Illuminate\View\View->render() #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('F:\xampp\htdocs...') #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('F:\xampp\htdocs...', Array) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('F:\xampp\htdocs...', Array) #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents() #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Http\Response.php(70): Illuminate\View\View->render() #11 F:\xampp\htdocs\Forex\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'indexModify', Object(Illuminate\View\View)) #15 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'indexModify', Array) #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('news', 'tin_tn') #17 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #18 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #19 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #20 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #23 {main} [] []
[2014-09-11 04:15:53] log.ERROR: exception 'InvalidArgumentException' with message 'Value must be provided.' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:282 Stack trace: #0 F:\xampp\htdocs\Forex\app\models\TinTuc.php(143): Illuminate\Database\Query\Builder->where('id', '<>', NULL) #1 F:\xampp\htdocs\Forex\app\controllers\GuestController.php(365): TinTuc::SelectRelate('views', NULL, NULL, 5) #2 [internal function]: GuestController->indexModify('news', 'tin_tn') #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('indexModify', Array) #5 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'indexModify', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('news', 'tin_tn') #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2014-09-11 04:28:05] log.ERROR: exception 'ErrorException' with message 'Undefined variable: viewsthreads' in F:\xampp\htdocs\Forex\app\storage\views\859a5d33391c0650d2593b80f4a21d06:8 Stack trace: #0 F:\xampp\htdocs\Forex\app\storage\views\859a5d33391c0650d2593b80f4a21d06(8): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'F:\xampp\htdocs...', 8, Array) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('F:\xampp\htdocs...') #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('F:\xampp\htdocs...', Array) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('F:\xampp\htdocs...', Array) #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents() #5 F:\xampp\htdocs\Forex\app\storage\views\06b70cf16aefbbea516c40d576b7affc(45): Illuminate\View\View->render() #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('F:\xampp\htdocs...') #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('F:\xampp\htdocs...', Array) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('F:\xampp\htdocs...', Array) #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents() #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Http\Response.php(70): Illuminate\View\View->render() #11 F:\xampp\htdocs\Forex\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'index', Object(Illuminate\View\View)) #15 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('sanpham') #17 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #18 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #19 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #20 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #23 {main} [] []
[2014-09-11 04:28:49] log.ERROR: exception 'ErrorException' with message 'Undefined variable: id' in F:\xampp\htdocs\Forex\app\controllers\GuestController.php:99 Stack trace: #0 F:\xampp\htdocs\Forex\app\controllers\GuestController.php(99): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'F:\xampp\htdocs...', 99, Array) #1 [internal function]: GuestController->index('sanpham') #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('index', Array) #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('sanpham') #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-09-11 15:33:47] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class User contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\Auth\UserInterface::getRememberToken, Illuminate\Auth\UserInterface::setRememberToken, Illuminate\Auth\UserInterface::getRememberTokenName)' in F:\xampp\htdocs\Forex\app\models\User.php:131 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-09-11 15:36:58] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class User contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\Auth\UserInterface::getRememberToken, Illuminate\Auth\UserInterface::setRememberToken, Illuminate\Auth\UserInterface::getRememberTokenName, ...)' in F:\xampp\htdocs\Forex\app\models\User.php:101 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-09-11 15:41:35] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class User contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\Auth\UserInterface::getRememberToken, Illuminate\Auth\UserInterface::setRememberToken, Illuminate\Auth\UserInterface::getRememberTokenName, ...)' in F:\xampp\htdocs\Forex\app\models\User.php:101 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-09-11 15:41:42] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class User contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\Auth\UserInterface::getRememberToken, Illuminate\Auth\UserInterface::setRememberToken, Illuminate\Auth\UserInterface::getRememberTokenName, ...)' in F:\xampp\htdocs\Forex\app\models\User.php:101 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-09-11 15:42:19] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in F:\xampp\htdocs\Forex\app\models\User.php:26 Stack trace: #0 F:\xampp\htdocs\Forex\app\models\User.php(26): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'F:\xampp\htdocs...', 26, Array) #1 F:\xampp\htdocs\Forex\app\controllers\HomeController.php(27): User->Authenticate(Array) #2 [internal function]: HomeController->authenticate() #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('authenticate', Array) #5 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'authenticate', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2014-09-11 15:43:04] log.ERROR: exception 'ErrorException' with message 'Argument 1 passed to Illuminate\Auth\Guard::attempt() must be of the type array, object given' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Auth\Guard.php:296 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(296): Illuminate\Exception\Handler->handleError(4096, 'Argument 1 pass...', 'F:\xampp\htdocs...', 296, Array) #1 [internal function]: Illuminate\Auth\Guard->attempt(Object(stdClass)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Manager.php(129): call_user_func_array(Array, Array) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Support\Manager->__call('attempt', Array) #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Auth\AuthManager->attempt(Object(stdClass)) #5 F:\xampp\htdocs\Forex\app\models\User.php(31): Illuminate\Support\Facades\Facade::__callStatic('attempt', Array) #6 F:\xampp\htdocs\Forex\app\models\User.php(31): Illuminate\Support\Facades\Auth::attempt(Object(stdClass)) #7 F:\xampp\htdocs\Forex\app\controllers\HomeController.php(27): User->Authenticate(Array) #8 [internal function]: HomeController->authenticate() #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('authenticate', Array) #11 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'authenticate', Array) #12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #15 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #16 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #17 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #18 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #19 {main} [] []
[2014-09-11 15:45:15] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column '_token' in 'where clause'' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connection.php:272 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connection.php(272): PDO->prepare('select * from `...') #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select * from `...', Array) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select * from `...', Array) #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect() #5 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array) #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(441): Illuminate\Database\Query\Builder->get(Array) #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(132): Illuminate\Database\Eloquent\Builder->getModels(Array) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(108): Illuminate\Database\Eloquent\Builder->get(Array) #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Auth\EloquentUserProvider.php(94): Illuminate\Database\Eloquent\Builder->first() #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(300): Illuminate\Auth\EloquentUserProvider->retrieveByCredentials(Array) #11 [internal function]: Illuminate\Auth\Guard->attempt(Array) #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Manager.php(129): call_user_func_array(Array, Array) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Support\Manager->__call('attempt', Array) #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Auth\AuthManager->attempt(Array) #15 F:\xampp\htdocs\Forex\app\models\User.php(31): Illuminate\Support\Facades\Facade::__callStatic('attempt', Array) #16 F:\xampp\htdocs\Forex\app\models\User.php(31): Illuminate\Support\Facades\Auth::attempt(Array) #17 F:\xampp\htdocs\Forex\app\controllers\HomeController.php(27): User->Authenticate(Array) #18 [internal function]: HomeController->authenticate() #19 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #20 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('authenticate', Array) #21 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'authenticate', Array) #22 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #23 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #24 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #25 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #26 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #27 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #28 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #29 {main} Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column '_token' in 'where clause' (SQL: select * from `nguoidung` where `_token` = ? and `username` = ? limit 1) (Bindings: array (   0 => '0AJ5MvpYUWGp8RAKG0naS8KeEcWyQ1DJrMcfgUNe',   1 => 'admin', ))' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select * from `...', Array) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select * from `...', Array) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect() #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array) #5 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(441): Illuminate\Database\Query\Builder->get(Array) #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(132): Illuminate\Database\Eloquent\Builder->getModels(Array) #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(108): Illuminate\Database\Eloquent\Builder->get(Array) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Auth\EloquentUserProvider.php(94): Illuminate\Database\Eloquent\Builder->first() #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(300): Illuminate\Auth\EloquentUserProvider->retrieveByCredentials(Array) #10 [internal function]: Illuminate\Auth\Guard->attempt(Array) #11 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Manager.php(129): call_user_func_array(Array, Array) #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Support\Manager->__call('attempt', Array) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Auth\AuthManager->attempt(Array) #14 F:\xampp\htdocs\Forex\app\models\User.php(31): Illuminate\Support\Facades\Facade::__callStatic('attempt', Array) #15 F:\xampp\htdocs\Forex\app\models\User.php(31): Illuminate\Support\Facades\Auth::attempt(Array) #16 F:\xampp\htdocs\Forex\app\controllers\HomeController.php(27): User->Authenticate(Array) #17 [internal function]: HomeController->authenticate() #18 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #19 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('authenticate', Array) #20 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'authenticate', Array) #21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #22 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #23 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #24 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #25 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #26 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #27 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #28 {main} [] []
[2014-09-11 15:46:48] log.ERROR: exception 'Symfony\Component\Routing\Exception\RouteNotFoundException' with message 'Unable to generate a URL for the named route "login" as such route does not exist.' in F:\xampp\htdocs\Forex\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php:134 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php(192): Symfony\Component\Routing\Generator\UrlGenerator->generate('login', Array, true) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Redirector.php(157): Illuminate\Routing\UrlGenerator->route('login', Array) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Routing\Redirector->route('login') #3 F:\xampp\htdocs\Forex\app\controllers\HomeController.php(33): Illuminate\Support\Facades\Facade::__callStatic('route', Array) #4 F:\xampp\htdocs\Forex\app\controllers\HomeController.php(33): Illuminate\Support\Facades\Redirect::route('login') #5 [internal function]: HomeController->authenticate() #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('authenticate', Array) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'authenticate', Array) #9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #11 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #15 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #16 {main} [] []
[2014-09-11 15:47:23] log.ERROR: exception 'Symfony\Component\Routing\Exception\RouteNotFoundException' with message 'Unable to generate a URL for the named route "/login" as such route does not exist.' in F:\xampp\htdocs\Forex\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php:134 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php(192): Symfony\Component\Routing\Generator\UrlGenerator->generate('/login', Array, true) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Redirector.php(157): Illuminate\Routing\UrlGenerator->route('/login', Array) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Routing\Redirector->route('/login') #3 F:\xampp\htdocs\Forex\app\controllers\HomeController.php(33): Illuminate\Support\Facades\Facade::__callStatic('route', Array) #4 F:\xampp\htdocs\Forex\app\controllers\HomeController.php(33): Illuminate\Support\Facades\Redirect::route('/login') #5 [internal function]: HomeController->authenticate() #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('authenticate', Array) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'authenticate', Array) #9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #11 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #15 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #16 {main} [] []
[2014-09-11 15:49:15] log.ERROR: exception 'Symfony\Component\Routing\Exception\RouteNotFoundException' with message 'Unable to generate a URL for the named route "http://localhost/Forex/login" as such route does not exist.' in F:\xampp\htdocs\Forex\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php:134 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php(192): Symfony\Component\Routing\Generator\UrlGenerator->generate('http://localhos...', Array, true) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Redirector.php(157): Illuminate\Routing\UrlGenerator->route('http://localhos...', Array) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Routing\Redirector->route('http://localhos...') #3 F:\xampp\htdocs\Forex\app\controllers\HomeController.php(33): Illuminate\Support\Facades\Facade::__callStatic('route', Array) #4 F:\xampp\htdocs\Forex\app\controllers\HomeController.php(33): Illuminate\Support\Facades\Redirect::route('http://localhos...') #5 [internal function]: HomeController->authenticate() #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('authenticate', Array) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'authenticate', Array) #9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #11 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #15 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #16 {main} [] []
[2014-09-11 15:50:07] log.ERROR: exception 'Symfony\Component\Routing\Exception\RouteNotFoundException' with message 'Unable to generate a URL for the named route "http://localhost/Forex/login" as such route does not exist.' in F:\xampp\htdocs\Forex\vendor\symfony\routing\Symfony\Component\Routing\Generator\UrlGenerator.php:134 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php(192): Symfony\Component\Routing\Generator\UrlGenerator->generate('http://localhos...', Array, true) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Redirector.php(157): Illuminate\Routing\UrlGenerator->route('http://localhos...', Array) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Routing\Redirector->route('http://localhos...') #3 F:\xampp\htdocs\Forex\app\controllers\HomeController.php(33): Illuminate\Support\Facades\Facade::__callStatic('route', Array) #4 F:\xampp\htdocs\Forex\app\controllers\HomeController.php(33): Illuminate\Support\Facades\Redirect::route('http://localhos...') #5 [internal function]: HomeController->authenticate() #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('authenticate', Array) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'authenticate', Array) #9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #11 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #15 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #16 {main} [] []
[2014-09-11 16:00:25] log.ERROR: exception 'ErrorException' with message 'Undefined variable: table' in F:\xampp\htdocs\Forex\app\models\User.php:24 Stack trace: #0 F:\xampp\htdocs\Forex\app\models\User.php(24): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'F:\xampp\htdocs...', 24, Array) #1 F:\xampp\htdocs\Forex\app\controllers\HomeController.php(30): User->Authenticate(Array) #2 [internal function]: HomeController->authenticate() #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('authenticate', Array) #5 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'authenticate', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2014-09-11 16:19:21] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Interface 'UserInterface' not found' in F:\xampp\htdocs\Forex\app\models\User.php:6 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-09-11 16:19:34] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Interface 'RemindableInterface' not found' in F:\xampp\htdocs\Forex\app\models\User.php:6 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-09-11 16:19:41] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class User contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\Auth\UserInterface::getRememberToken, Illuminate\Auth\UserInterface::setRememberToken, Illuminate\Auth\UserInterface::getRememberTokenName, ...)' in F:\xampp\htdocs\Forex\app\models\User.php:91 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-09-11 16:22:11] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class User contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Auth\Reminders\RemindableInterface::getReminderEmail)' in F:\xampp\htdocs\Forex\app\models\User.php:99 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-09-11 16:23:07] log.ERROR: exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::getRole()' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:1658 Stack trace: #0 [internal function]: Illuminate\Database\Query\Builder->__call('getRole', Array) #1 [internal function]: Illuminate\Database\Query\Builder->getRole() #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('getRole', Array) #4 [internal function]: Illuminate\Database\Eloquent\Builder->getRole() #5 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2653): call_user_func_array(Array, Array) #6 F:\xampp\htdocs\Forex\app\routes.php(68): Illuminate\Database\Eloquent\Model->__call('getRole', Array) #7 F:\xampp\htdocs\Forex\app\routes.php(68): User->getRole() #8 [internal function]: {closure}() #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(650): call_user_func(Object(Closure)) #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(209): Illuminate\Routing\Router->group(Array, Object(Closure)) #11 F:\xampp\htdocs\Forex\app\routes.php(82): Illuminate\Support\Facades\Facade::__callStatic('group', Array) #12 F:\xampp\htdocs\Forex\app\routes.php(82): Illuminate\Support\Facades\Route::group(Array, Object(Closure)) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\start.php(253): require('F:\xampp\htdocs...') #14 F:\xampp\htdocs\Forex\bootstrap\start.php(61): require('F:\xampp\htdocs...') #15 F:\xampp\htdocs\Forex\index.php(35): require_once('F:\xampp\htdocs...') #16 {main} [] []
[2014-09-11 17:02:01] log.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it. ' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:47 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(47): PDO->__construct('mysql:host=loca...', 'root', '', Array) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(41): Illuminate\Database\Connectors\MySqlConnector->connect(Array) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(128): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql') #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(64): Illuminate\Database\DatabaseManager->makeConnection('mysql') #5 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(242): Illuminate\Database\DatabaseManager->connection() #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Database\DatabaseManager->__call('table', Array) #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Database\DatabaseManager->table('contact') #8 F:\xampp\htdocs\Forex\app\models\Contact.php(18): Illuminate\Support\Facades\Facade::__callStatic('table', Array) #9 F:\xampp\htdocs\Forex\app\models\Contact.php(18): Illuminate\Support\Facades\DB::table('contact') #10 F:\xampp\htdocs\Forex\app\controllers\GuestController.php(8): Contact::Select() #11 [internal function]: GuestController->index('login') #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('index', Array) #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('login') #16 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2014-09-11 17:14:00] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list'' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connection.php:351 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connection.php(351): PDO->prepare('update `nguoidu...') #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'update `nguoidu...', Array) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connection.php(356): Illuminate\Database\Connection->run('update `nguoidu...', Array, Object(Closure)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connection.php(301): Illuminate\Database\Connection->affectingStatement('update `nguoidu...', Array) #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1459): Illuminate\Database\Connection->update('update `nguoidu...', Array) #5 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1196): Illuminate\Database\Eloquent\Builder->update(Array) #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1132): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder)) #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Auth\EloquentUserProvider.php(73): Illuminate\Database\Eloquent\Model->save() #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(491): Illuminate\Auth\EloquentUserProvider->updateRememberToken(Object(User), '6rjcCR8NAcaXyqW...') #10 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(451): Illuminate\Auth\Guard->refreshRememberToken(Object(User)) #11 [internal function]: Illuminate\Auth\Guard->logout() #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Manager.php(129): call_user_func_array(Array, Array) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(203): Illuminate\Support\Manager->__call('logout', Array) #14 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(203): Illuminate\Auth\AuthManager->logout() #15 F:\xampp\htdocs\Forex\app\controllers\HomeController.php(6): Illuminate\Support\Facades\Facade::__callStatic('logout', Array) #16 F:\xampp\htdocs\Forex\app\controllers\HomeController.php(6): Illuminate\Support\Facades\Auth::logout() #17 F:\xampp\htdocs\Forex\app\controllers\GuestController.php(205): HomeController->getLogout() #18 [internal function]: GuestController->index('logout') #19 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #20 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('index', Array) #21 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #22 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('logout') #23 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #24 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #25 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #26 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #27 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #28 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #29 {main} Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: update `nguoidung` set `remember_token` = ?, `updated_at` = ? where `id` = ?) (Bindings: array (   0 => '6rjcCR8NAcaXyqWb5BT9kPXKfc72fNdXwUGMFAOpGnoMVdhgZwlxkLu6PuOh',   1 => '2014-09-11 17:14:00',   2 => 1, ))' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'update `nguoidu...', Array) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connection.php(356): Illuminate\Database\Connection->run('update `nguoidu...', Array, Object(Closure)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Connection.php(301): Illuminate\Database\Connection->affectingStatement('update `nguoidu...', Array) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1459): Illuminate\Database\Connection->update('update `nguoidu...', Array) #4 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #5 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1196): Illuminate\Database\Eloquent\Builder->update(Array) #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1132): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder)) #7 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Auth\EloquentUserProvider.php(73): Illuminate\Database\Eloquent\Model->save() #8 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(491): Illuminate\Auth\EloquentUserProvider->updateRememberToken(Object(User), '6rjcCR8NAcaXyqW...') #9 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(451): Illuminate\Auth\Guard->refreshRememberToken(Object(User)) #10 [internal function]: Illuminate\Auth\Guard->logout() #11 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Manager.php(129): call_user_func_array(Array, Array) #12 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(203): Illuminate\Support\Manager->__call('logout', Array) #13 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(203): Illuminate\Auth\AuthManager->logout() #14 F:\xampp\htdocs\Forex\app\controllers\HomeController.php(6): Illuminate\Support\Facades\Facade::__callStatic('logout', Array) #15 F:\xampp\htdocs\Forex\app\controllers\HomeController.php(6): Illuminate\Support\Facades\Auth::logout() #16 F:\xampp\htdocs\Forex\app\controllers\GuestController.php(205): HomeController->getLogout() #17 [internal function]: GuestController->index('logout') #18 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #19 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('index', Array) #20 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('logout') #22 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #23 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #24 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #25 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #26 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #27 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #28 {main} [] []
[2014-09-11 17:29:04] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in F:\xampp\htdocs\Forex\app\routes.php:44 Stack trace: #0 F:\xampp\htdocs\Forex\app\routes.php(44): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'F:\xampp\htdocs...', 44, Array) #1 [internal function]: {closure}() #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(650): call_user_func(Object(Closure)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(209): Illuminate\Routing\Router->group(Array, Object(Closure)) #4 F:\xampp\htdocs\Forex\app\routes.php(70): Illuminate\Support\Facades\Facade::__callStatic('group', Array) #5 F:\xampp\htdocs\Forex\app\routes.php(70): Illuminate\Support\Facades\Route::group(Array, Object(Closure)) #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\start.php(253): require('F:\xampp\htdocs...') #7 F:\xampp\htdocs\Forex\bootstrap\start.php(61): require('F:\xampp\htdocs...') #8 F:\xampp\htdocs\Forex\index.php(35): require_once('F:\xampp\htdocs...') #9 {main} [] []
[2014-09-11 17:29:19] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in F:\xampp\htdocs\Forex\app\routes.php:44 Stack trace: #0 F:\xampp\htdocs\Forex\app\routes.php(44): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'F:\xampp\htdocs...', 44, Array) #1 [internal function]: {closure}() #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(650): call_user_func(Object(Closure)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(209): Illuminate\Routing\Router->group(Array, Object(Closure)) #4 F:\xampp\htdocs\Forex\app\routes.php(70): Illuminate\Support\Facades\Facade::__callStatic('group', Array) #5 F:\xampp\htdocs\Forex\app\routes.php(70): Illuminate\Support\Facades\Route::group(Array, Object(Closure)) #6 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\start.php(253): require('F:\xampp\htdocs...') #7 F:\xampp\htdocs\Forex\bootstrap\start.php(61): require('F:\xampp\htdocs...') #8 F:\xampp\htdocs\Forex\index.php(35): require_once('F:\xampp\htdocs...') #9 {main} [] []
[2014-09-11 17:30:13] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:30:56] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:31:18] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Routing\Router::to()' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:206 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-09-11 17:31:20] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Routing\Router::to()' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:206 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-09-11 17:31:22] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Routing\Router::to()' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:206 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-09-11 17:31:40] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:31:42] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:32:08] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:32:22] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:32:24] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:34:27] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:34:29] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:35:04] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:35:05] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:35:06] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:35:12] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:36:07] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:36:33] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:36:35] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:36:44] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:37:30] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:38:30] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:39:18] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:44:39] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-09-11 17:44:52] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 F:\xampp\htdocs\Forex\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 F:\xampp\htdocs\Forex\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
