[2014-04-25 00:06:30] log.ERROR: exception 'InvalidArgumentException' with message 'Value must be provided.' in D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:282
Stack trace:
#0 D:\All Program\xampp\htdocs\vpk_Demo\app\controllers\GridController.php(426): Illuminate\Database\Query\Builder->where('diemsv', '<>', NULL)
#1 [internal function]: GridController->postDemdslop()
#2 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#3 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postDemdslop', Array)
#4 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postDemdslop', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#6 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#7 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#8 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 D:\All Program\xampp\htdocs\vpk_Demo\index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-04-25 00:06:35] log.ERROR: exception 'InvalidArgumentException' with message 'Value must be provided.' in D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:282
Stack trace:
#0 D:\All Program\xampp\htdocs\vpk_Demo\app\controllers\GridController.php(426): Illuminate\Database\Query\Builder->where('diemsv', '<>', NULL)
#1 [internal function]: GridController->postDemdslop()
#2 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#3 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postDemdslop', Array)
#4 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postDemdslop', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#6 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#7 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#8 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 D:\All Program\xampp\htdocs\vpk_Demo\index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-04-25 00:07:37] log.ERROR: exception 'InvalidArgumentException' with message 'Value must be provided.' in D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:282
Stack trace:
#0 D:\All Program\xampp\htdocs\vpk_Demo\app\controllers\GridController.php(426): Illuminate\Database\Query\Builder->where('diemsv', '<>', NULL)
#1 [internal function]: GridController->postDemdslop()
#2 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#3 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postDemdslop', Array)
#4 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postDemdslop', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#6 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#7 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#8 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 D:\All Program\xampp\htdocs\vpk_Demo\index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-04-25 00:09:38] log.ERROR: exception 'InvalidArgumentException' with message 'Value must be provided.' in D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:282
Stack trace:
#0 D:\All Program\xampp\htdocs\vpk_Demo\app\storage\views\747265efaaa4b0e56e2d8802b01aec9b(24): Illuminate\Database\Query\Builder->where('diemsv', '<>', NULL)
#1 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('D:\All Program\...')
#2 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\All Program\...', Array)
#3 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('D:\All Program\...', Array)
#4 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents()
#5 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Http\Response.php(70): Illuminate\View\View->render()
#6 D:\All Program\xampp\htdocs\vpk_Demo\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getChamdiem', Object(Illuminate\View\View))
#10 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getChamdiem', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#12 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#13 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#14 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 D:\All Program\xampp\htdocs\vpk_Demo\index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2014-04-25 00:10:10] log.ERROR: exception 'InvalidArgumentException' with message 'Value must be provided.' in D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:282
Stack trace:
#0 D:\All Program\xampp\htdocs\vpk_Demo\app\storage\views\747265efaaa4b0e56e2d8802b01aec9b(24): Illuminate\Database\Query\Builder->where('diemsv', '<>', NULL)
#1 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('D:\All Program\...')
#2 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\All Program\...', Array)
#3 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('D:\All Program\...', Array)
#4 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents()
#5 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Http\Response.php(70): Illuminate\View\View->render()
#6 D:\All Program\xampp\htdocs\vpk_Demo\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getChamdiem', Object(Illuminate\View\View))
#10 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getChamdiem', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#12 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#13 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#14 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 D:\All Program\xampp\htdocs\vpk_Demo\index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2014-04-25 00:13:40] log.ERROR: exception 'InvalidArgumentException' with message 'Value must be provided.' in D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:282
Stack trace:
#0 D:\All Program\xampp\htdocs\vpk_Demo\app\storage\views\747265efaaa4b0e56e2d8802b01aec9b(24): Illuminate\Database\Query\Builder->where('diemsv', '<>', NULL)
#1 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('D:\All Program\...')
#2 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\All Program\...', Array)
#3 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('D:\All Program\...', Array)
#4 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents()
#5 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Http\Response.php(70): Illuminate\View\View->render()
#6 D:\All Program\xampp\htdocs\vpk_Demo\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getChamdiem', Object(Illuminate\View\View))
#10 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getChamdiem', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#12 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#13 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#14 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 D:\All Program\xampp\htdocs\vpk_Demo\index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2014-04-25 00:13:54] log.ERROR: exception 'InvalidArgumentException' with message 'Value must be provided.' in D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:282
Stack trace:
#0 D:\All Program\xampp\htdocs\vpk_Demo\app\storage\views\747265efaaa4b0e56e2d8802b01aec9b(24): Illuminate\Database\Query\Builder->where('diemsv', '<>', NULL)
#1 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('D:\All Program\...')
#2 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\All Program\...', Array)
#3 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('D:\All Program\...', Array)
#4 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents()
#5 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Http\Response.php(70): Illuminate\View\View->render()
#6 D:\All Program\xampp\htdocs\vpk_Demo\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getChamdiem', Object(Illuminate\View\View))
#10 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getChamdiem', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#12 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#13 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#14 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 D:\All Program\xampp\htdocs\vpk_Demo\index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2014-04-25 00:36:38] log.ERROR: exception 'ErrorException' with message 'PDO::__construct(): MySQL server has gone away' in D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:47
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'PDO::__construc...', 'D:\All Program\...', 47, Array)
#1 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(47): PDO->__construct('mysql:host=loca...', 'root', '', Array)
#2 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#3 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(41): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#4 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(128): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#5 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(64): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#6 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2472): Illuminate\Database\DatabaseManager->connection(NULL)
#7 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2438): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#8 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1527): Illuminate\Database\Eloquent\Model->getConnection()
#9 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1461): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#10 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Auth\EloquentUserProvider.php(42): Illuminate\Database\Eloquent\Model->newQuery()
#11 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(121): Illuminate\Auth\EloquentUserProvider->retrieveById(0)
#12 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(82): Illuminate\Auth\Guard->user()
#13 [internal function]: Illuminate\Auth\Guard->check()
#14 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Support\Manager.php(129): call_user_func_array(Array, Array)
#15 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(203): Illuminate\Support\Manager->__call('check', Array)
#16 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(203): Illuminate\Auth\AuthManager->check()
#17 D:\All Program\xampp\htdocs\vpk_Demo\app\routes.php(136): Illuminate\Support\Facades\Facade::__callStatic('check', Array)
#18 D:\All Program\xampp\htdocs\vpk_Demo\app\routes.php(136): Illuminate\Support\Facades\Auth::check()
#19 [internal function]: {closure}()
#20 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(650): call_user_func(Object(Closure))
#21 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(209): Illuminate\Routing\Router->group(Array, Object(Closure))
#22 D:\All Program\xampp\htdocs\vpk_Demo\app\routes.php(176): Illuminate\Support\Facades\Facade::__callStatic('group', Array)
#23 D:\All Program\xampp\htdocs\vpk_Demo\app\routes.php(176): Illuminate\Support\Facades\Route::group(Array, Object(Closure))
#24 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Foundation\start.php(253): require('D:\All Program\...')
#25 D:\All Program\xampp\htdocs\vpk_Demo\bootstrap\start.php(61): require('D:\All Program\...')
#26 D:\All Program\xampp\htdocs\vpk_Demo\index.php(35): require_once('D:\All Program\...')
#27 {main}

Next exception 'PDOException' with message 'SQLSTATE[HY000] [2006] MySQL server has gone away' in D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:47
Stack trace:
#0 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(0): PDO->__construct()
#1 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(41): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(128): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#4 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(64): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#5 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2472): Illuminate\Database\DatabaseManager->connection(NULL)
#6 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2438): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#7 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1527): Illuminate\Database\Eloquent\Model->getConnection()
#8 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1461): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#9 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Auth\EloquentUserProvider.php(42): Illuminate\Database\Eloquent\Model->newQuery()
#10 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(121): Illuminate\Auth\EloquentUserProvider->retrieveById(0)
#11 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(82): Illuminate\Auth\Guard->user()
#12 [internal function]: Illuminate\Auth\Guard->check()
#13 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Support\Manager.php(129): call_user_func_array(Array, Array)
#14 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(203): Illuminate\Support\Manager->__call('check', Array)
#15 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(203): Illuminate\Auth\AuthManager->check()
#16 D:\All Program\xampp\htdocs\vpk_Demo\app\routes.php(136): Illuminate\Support\Facades\Facade::__callStatic('check', Array)
#17 D:\All Program\xampp\htdocs\vpk_Demo\app\routes.php(136): Illuminate\Support\Facades\Auth::check()
#18 [internal function]: {closure}()
#19 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Routing\Router.php(650): call_user_func(Object(Closure))
#20 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(209): Illuminate\Routing\Router->group(Array, Object(Closure))
#21 D:\All Program\xampp\htdocs\vpk_Demo\app\routes.php(176): Illuminate\Support\Facades\Facade::__callStatic('group', Array)
#22 D:\All Program\xampp\htdocs\vpk_Demo\app\routes.php(176): Illuminate\Support\Facades\Route::group(Array, Object(Closure))
#23 D:\All Program\xampp\htdocs\vpk_Demo\vendor\laravel\framework\src\Illuminate\Foundation\start.php(253): require('D:\All Program\...')
#24 D:\All Program\xampp\htdocs\vpk_Demo\bootstrap\start.php(61): require('D:\All Program\...')
#25 D:\All Program\xampp\htdocs\vpk_Demo\index.php(35): require_once('D:\All Program\...')
#26 {main} [] []
