[2014-02-15 10:28:30] log.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('vpk'@'localhost') does not exist' in C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php:272
Stack trace:
#0 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(272): PDO->prepare('select * from `...')
#1 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select * from `...', Array)
#2 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#3 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select * from `...', Array)
#4 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#5 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#6 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(990): Illuminate\Database\Query\Builder->get(Array)
#7 C:\xampp\htdocs\vpk_mau\app\routes.php(36): Illuminate\Database\Query\Builder->first()
#8 [internal function]: {closure}()
#9 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#10 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#11 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 C:\xampp\htdocs\vpk_mau\index.php(49): Illuminate\Foundation\Application->run()
#15 {main}

Next exception 'Exception' with message 'SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('vpk'@'localhost') does not exist (SQL: select * from `vcanbo` where `macb` = ? limit 1) (Bindings: array (
  0 => '1101706',
))' in C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select * from `...', Array)
#1 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#2 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select * from `...', Array)
#3 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(990): Illuminate\Database\Query\Builder->get(Array)
#6 C:\xampp\htdocs\vpk_mau\app\routes.php(36): Illuminate\Database\Query\Builder->first()
#7 [internal function]: {closure}()
#8 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#9 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#10 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 C:\xampp\htdocs\vpk_mau\index.php(49): Illuminate\Foundation\Application->run()
#14 {main} [] []
[2014-02-15 10:30:08] log.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('vpk'@'localhost') does not exist' in C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php:272
Stack trace:
#0 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(272): PDO->prepare('select * from `...')
#1 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select * from `...', Array)
#2 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#3 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select * from `...', Array)
#4 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#5 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#6 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(990): Illuminate\Database\Query\Builder->get(Array)
#7 C:\xampp\htdocs\vpk_mau\app\routes.php(36): Illuminate\Database\Query\Builder->first()
#8 [internal function]: {closure}()
#9 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#10 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#11 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 C:\xampp\htdocs\vpk_mau\index.php(49): Illuminate\Foundation\Application->run()
#15 {main}

Next exception 'Exception' with message 'SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('vpk'@'localhost') does not exist (SQL: select * from `vcanbo` where `macb` = ? limit 1) (Bindings: array (
  0 => '1101706',
))' in C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select * from `...', Array)
#1 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#2 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select * from `...', Array)
#3 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(990): Illuminate\Database\Query\Builder->get(Array)
#6 C:\xampp\htdocs\vpk_mau\app\routes.php(36): Illuminate\Database\Query\Builder->first()
#7 [internal function]: {closure}()
#8 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#9 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#10 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 C:\xampp\htdocs\vpk_mau\index.php(49): Illuminate\Foundation\Application->run()
#14 {main} [] []
[2014-02-15 10:31:48] log.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('vpk'@'localhost') does not exist' in C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php:272
Stack trace:
#0 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(272): PDO->prepare('select * from `...')
#1 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select * from `...', Array)
#2 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#3 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select * from `...', Array)
#4 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#5 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#6 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(990): Illuminate\Database\Query\Builder->get(Array)
#7 C:\xampp\htdocs\vpk_mau\app\routes.php(36): Illuminate\Database\Query\Builder->first()
#8 [internal function]: {closure}()
#9 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#10 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#11 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 C:\xampp\htdocs\vpk_mau\index.php(49): Illuminate\Foundation\Application->run()
#15 {main}

Next exception 'Exception' with message 'SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('vpk'@'localhost') does not exist (SQL: select * from `vcanbo` where `macb` = ? limit 1) (Bindings: array (
  0 => '1101706',
))' in C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select * from `...', Array)
#1 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#2 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select * from `...', Array)
#3 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(990): Illuminate\Database\Query\Builder->get(Array)
#6 C:\xampp\htdocs\vpk_mau\app\routes.php(36): Illuminate\Database\Query\Builder->first()
#7 [internal function]: {closure}()
#8 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#9 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#10 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 C:\xampp\htdocs\vpk_mau\index.php(49): Illuminate\Foundation\Application->run()
#14 {main} [] []
[2014-02-15 10:39:21] log.ERROR: exception 'ErrorException' with message 'Undefined property: stdClass::$ma_ttht' in C:\xampp\htdocs\vpk_mau\app\routes.php:37
Stack trace:
#0 C:\xampp\htdocs\vpk_mau\app\routes.php(37): Illuminate\Exception\Handler->handleError(8, 'Undefined prope...', 'C:\xampp\htdocs...', 37, Array)
#1 [internal function]: {closure}()
#2 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#3 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#4 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#5 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 C:\xampp\htdocs\vpk_mau\index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []
[2014-02-15 10:39:51] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '{'' in C:\xampp\htdocs\vpk_mau\app\routes.php:37
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2014-02-15 10:40:18] log.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('vpk'@'localhost') does not exist' in C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php:272
Stack trace:
#0 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(272): PDO->prepare('select * from `...')
#1 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select * from `...', Array)
#2 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#3 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select * from `...', Array)
#4 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#5 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#6 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(990): Illuminate\Database\Query\Builder->get(Array)
#7 C:\xampp\htdocs\vpk_mau\app\models\User.php(57): Illuminate\Database\Query\Builder->first()
#8 C:\xampp\htdocs\vpk_mau\app\routes.php(137): User->getRole()
#9 [internal function]: {closure}()
#10 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Router.php(650): call_user_func(Object(Closure))
#11 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(209): Illuminate\Routing\Router->group(Array, Object(Closure))
#12 C:\xampp\htdocs\vpk_mau\app\routes.php(174): Illuminate\Support\Facades\Facade::__callStatic('group', Array)
#13 C:\xampp\htdocs\vpk_mau\app\routes.php(174): Illuminate\Support\Facades\Route::group(Array, Object(Closure))
#14 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Foundation\start.php(253): require('C:\xampp\htdocs...')
#15 C:\xampp\htdocs\vpk_mau\bootstrap\start.php(61): require('C:\xampp\htdocs...')
#16 C:\xampp\htdocs\vpk_mau\index.php(35): require_once('C:\xampp\htdocs...')
#17 {main}

Next exception 'Exception' with message 'SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('vpk'@'localhost') does not exist (SQL: select * from `vcanbo` where `macb` = ? limit 1) (Bindings: array (
  0 => '1101706',
))' in C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select * from `...', Array)
#1 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#2 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select * from `...', Array)
#3 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(990): Illuminate\Database\Query\Builder->get(Array)
#6 C:\xampp\htdocs\vpk_mau\app\models\User.php(57): Illuminate\Database\Query\Builder->first()
#7 C:\xampp\htdocs\vpk_mau\app\routes.php(137): User->getRole()
#8 [internal function]: {closure}()
#9 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Routing\Router.php(650): call_user_func(Object(Closure))
#10 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(209): Illuminate\Routing\Router->group(Array, Object(Closure))
#11 C:\xampp\htdocs\vpk_mau\app\routes.php(174): Illuminate\Support\Facades\Facade::__callStatic('group', Array)
#12 C:\xampp\htdocs\vpk_mau\app\routes.php(174): Illuminate\Support\Facades\Route::group(Array, Object(Closure))
#13 C:\xampp\htdocs\vpk_mau\vendor\laravel\framework\src\Illuminate\Foundation\start.php(253): require('C:\xampp\htdocs...')
#14 C:\xampp\htdocs\vpk_mau\bootstrap\start.php(61): require('C:\xampp\htdocs...')
#15 C:\xampp\htdocs\vpk_mau\index.php(35): require_once('C:\xampp\htdocs...')
#16 {main} [] []
